### ISSUE TITLE
unreliable/unstable private browsing detection/settings switching

### ISSUE THREAD

**Issue by TheRealMarnes** [TheRealMarnes/private-browsing-proxy#1]

**Comment by CHEF-KOCH** [comment]
It would be also help if there is an detection in case someone start FF by default in private modus. 

Is there an solution available or an other extension/addon you can recommend in the meantime?

**Comment by TheRealMarnes** [comment]
I think last time I tried there was something preventing addons from detecting permanent private browsing mode. Maybe they've fixed that by now. I'll have another look at it soon.

**Comment by TheRealMarnes** [comment]
Actually, permanent private browsing defeats the purpose of this addon. If you're gonna turn it on and use ff in private mode constantly, you can just as well also set your proxy configuration and leave it on. This addon is only meant for if you constantly switch back and forth between normal mode and non-permanent private mode.

**Comment by CHEF-KOCH** [comment]
Okay, thanks for the answer. Well my intent to use private modus all the time is that I use two profiles (one for normal surfing and one for sites I need to login and such). But you're absolutely right, I could simply use a proxy addon and run them all the time.

Anyway I like your addon interface, clean and simply, maybe I will found a similar one that offers that too - generally I care much about my system resources and that was also one of a goal why I used your stuff. 

CK

**Comment by TheRealMarnes** [comment]
Why do you need an addon for your proxy? Do you have to switch between multiple proxies with the flick of a switch or something?

**Comment by CHEF-KOCH** [comment]
I try to 'cheat' on my mobile data provider, that is all. The problem is that my provider seems to use a transparent proxy. I now use Proxy Switcher (IP finder) which also works separate for normal browsing and safebrowsing.  

For the rest I'm using OpenVPN. 

Sorry for the late answer.

**Comment by TheRealMarnes** [comment]
Link please? If there's already a better addon for this out there that also has more users already, it'd be better to drop this project (which I kinda want to do anyway). All I can find is https://addons.mozilla.org/en-US/firefox/addon/proxy-finder-ip-switcher/ which doesn't seem to have that private browsing feature (and has a slightly different name :P )

**Comment by CHEF-KOCH** [comment]
You're link is correct, yep, this addon doesn't offer an separate safe-browsing function like yours but you can use separate firefox profiles (yes I mean profiles) and add them, so you have two processes running, one for safe-browsing (I use safe-browsing by default) and a normal FF process. 

This addon works better for me and doesn't comes with bugs compared to FoxyProxy. And it works not only on Firefox, also works with mods like CyberFox, PaleMoon (needs some changes), Waterfox and such.

**Comment by TheRealMarnes** [comment]
Hmmm, too bad :/ I do wish someone would either take over this addon or make a better one already (with the same feature)

**Comment by CHEF-KOCH** [comment]
I will ask the developer to integrate an safe-browsing only feature. But I don't know if that is possible for future FF builds, since e10s is coming to final builds on FF at the end of 2015. Which means every tab creates it's own child process (like Opera/Chrome). Also old apis like XUL and such are gonna to be removed which is very annoying for hobby developer - because nobody knows if Googles engine really works on all situations.

**Comment by TheRealMarnes** [comment]
Yeah I know. It's not like e10s breaks or prevents functionality like this though, and as long webextensions gets equivalent functionality for what we do with xpcom or w/e it shouldn't be a problem either. I'm getting the feeling lots of people exaggerate the problem without really knowing what the result will be in practice...
